Test prod
Club-Alpin-Annecy/collectives-materiel pull request #3
Opened 2021-12-08 16:39 UTC by Trikzy7

Added some new pages about the "materiel" and the "stock":
_ Changed the dropdown menu "Gestion materiel"
_ Added all the equipment related models in DB
_ Added the "Gestion du matériel" pages: you can add equipment type, add equipment and add equipment models, you can also edit all of that

2022-01-02 17:20 UTC, fberu requested changes
Voici ma 1ère revue. L'essentiel est là dans ce lot 1 avec pour objectif de pouvoir gérer un stock de matériel.

Plusieurs points sont à revoir. Voir mes retours.
Globlament:

- La BDD a été mergée. Il faut qu'elle reste vide
- Sur toutes les pages où il y a un bouton "ajouter", "éditer", "supprimer", etc., respecter la même UI que pour les collectives et ajouter en bas de page un panneau "Administration"
- S'assurer que les champs saisis sont corrects (par ex s'assurer que si on demande un entier, c'est bien un entier qui est saisi) et afficher un message d'erreur explicite si ce n'est pas le cas
- Eviter les fenêtre modales
- Je suis perplexe sur l'ajout et l'affichage d'un modèle d'équipement. Il faudrait créer une page dédiée pour la création d'un modèle
- Toutes vos pages html ont le même nom. Remplacer un displayAll par un equipment_types, equipment_models.html, equipments.html. Les displayOne par equipment_type.html, equipment_model.html, equipment.html. Vos pages de création / édition devront être préfixées par edit_

La navigation est complexe. Sans doute des choses à revoir, on va mettre un expert UX/UI dessus :)

Sinon, attention aux fautes d'orthographe et aux innombrables lignes blanches inutiles

2022-01-02 17:20 UTC, fberu commented on collectives/templates/equipment/gestion/equipment/displayAll.html
> +        columns:[              //define the table columns
Reprendre la même UI que les collectives:
- ajouter un filtre en-tête avec comme champs: Type sous forme de combobox, Etat
![image](https://user-images.githubusercontent.com/59260805/147883388-acf85cbd-d1d9-49a3-bad1-a324580530c0.png)
- colonnes: photo du type d'équipement en 1ère colonne puis en 2ème colonne: le nom du modèle (affiché de la même manière que le titre d'une collective) puis à la ligne sa référence et son état

2022-01-02 17:20 UTC, fberu commented on collectives/templates/equipment/gestion/equipment/displayAll.html
> +            title:"Model",
Modèle

2022-01-02 17:20 UTC, fberu commented on collectives/templates/equipment/gestion/equipment/displayAll.html
> +    <p class="button button-primary button-small button-open-modal">Ajouter</p>
Ne pas afficher de fenêtre modale, mais une page dédiée, comme pour une collective

2022-01-02 17:20 UTC, fberu commented on collectives/models/equipment.py
> +    equipments = db.relationship(
ajouter un champ "Fabricant" (manufacturer en anglais)
ajouter la possibilité d'ajouter une photo

2022-01-09 14:34 UTC, gdaviet reviewed
J'ai rapidement relu la partie python. C'est plutôt très bien!

J'ai repris quelques commentaires de la revue précédente. Globalement c'est surtout des typos, quelques problèmes plus fondamentaux :
 - Modification via des requêtes GET
 - Utilisation de données utilisateurs pour former des chemins de fichiers
 - Stockage de prix en virgule flottante plutôt que décimale

En vrai rien de grave pour cette application, mais autant prendre des bonnes habitudes

2022-01-09 14:34 UTC, gdaviet commented on collectives/forms/equipment.py
> +            "pattern": "^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$",
La regexp n'accepte pas des prix au format français (virgule)

2022-01-09 14:34 UTC, gdaviet commented on collectives/models/equipment.py
> +    price = db.Column(db.Float)
De façon générale, ne pas stocker de données financières en float (qui n'a pas de représentation exacte pour la plupart des nombres avec virgule en base 10). Préférer le type Decimal ou stocker le nombre de centimes en Integer

2022-01-09 14:34 UTC, gdaviet commented on collectives/models/equipment.py
> +            filename = imgtypeequip.save(file, name="type-" + str(self.name) + ".")
Construire des chemins de fichier a part de strings fournies par l'utilisateur peut vite devenir un problème de sécurité. Il faudrait soit être sur  que le nom ne contient aucun caractère dangereux (compliqué), soit utiliser l'id dans le nom de fichier à la place (recommandé)

2022-01-09 14:34 UTC, gdaviet commented on collectives/models/equipment.py
> +    def nbModels(self):
Mix snake_case et  camelCase. Pas un gros problème, mais c'est bien de choisir une convention et de s'y tenir (ce qui n'est pas forcément le das dans le reste du code cela dit)

2022-01-09 14:34 UTC, gdaviet commented on collectives/models/equipment.py
> +        for aModel in list(self.models):
Le `list()` est-il nécéssaire ?

2022-01-09 14:34 UTC, gdaviet commented on collectives/models/role.py
> +    EquipmentVolonter = 22
Volonter->Volunteer

2022-01-10 15:44 UTC, Trikzy7 commented on collectives/templates/equipment/gestion/equipmentType/displayDetail.html
> +  <p class="button button-primary button-small">Ajouter</p>
Oui il y a une différence, nous avions pensé d'utiliser ce bouton dans le but d'afficher ou de cacher le formulaire d'ajout d'un modèle.

2022-01-11 14:07 UTC, hug0be commented on collectives/models/equipment.py
Il s'agirait d'un String avec un nombre de caractère fixe ?

2022-01-11 14:14 UTC, hug0be commented on collectives/models/equipment.py
> +    equipments = db.relationship(
La photo du type d'équipement ne suffit pas ?

2022-01-11 14:51 UTC, victor-lafarge commented on collectives/forms/equipment.py
> +    purchasePrice = DecimalField("Prix d'achat :")
Pourquoi un entier et non un decimal pour le prix de location ?

2022-01-12 13:05 UTC, Luckywee commented on collectives/templates/equipment/gestion/equipmentModel/displayAll.html
> +
Est ce qu'il faudrait quand meme laisser quelques sauts de ligne pour + de clarté, ou vraiment tous les supprimer ?

2022-01-15 12:35 UTC, merged